<?php
/**
 * TL_ROOT/system/modules/styleVis/languages/de/tl_settings.php 
 * 
 * TYPOlight extension: styleVis 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['showSingleStyles']['0'] = "Einzelne CSS-Stile anzeigen";
$GLOBALS['TL_LANG']['tl_settings']['showSingleStyles']['1'] = "Zeigt die Titel einzelner CSS-Stile im CSS-Editor auf Wunsch mit dem definierten CSS-Stil an (JavaScript benötigt). Wenn diese Option nicht aktiviert ist, werden die CSS-Titel immer mit dem jeweils definierten CSS-Stil angezeigt.";
$GLOBALS['TL_LANG']['tl_settings']['stylesheet_legend'] = "Stylesheet-Einstellungen";
 
?>
