<?php
/**
 * TL_ROOT/system/modules/styleVis/languages/de/tl_style.php 
 * 
 * TYPOlight extension: styleVis 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_style']['cssshow']['0'] = "CSS-Stil anzeigen";
$GLOBALS['TL_LANG']['tl_style']['cssshow']['1'] = "Zeigt den CSS-Stil für die aktuelle Definition an";
$GLOBALS['TL_LANG']['tl_style']['csshide']['0'] = "CSS-Stil verstecken";
$GLOBALS['TL_LANG']['tl_style']['csshide']['1'] = "Enfernt den CSS-Stil-Anzeige für die aktuelle Definition";
 
?>
